
version: "3"
services:

  parser:
    build: ./
    command: python rubbersearch/search_engine.py
    
  api:
    build: ./
    command: python rubbersearch/app.py
    ports:
      - "8000:8000"

  test:
    build: ./
    command: python -m unittest discover
